# vim:set ft=tmux:
## name: Ocean Breeze Theme
## author: Ivan Rudoy

# Pane border styling
# Border style settings
setw -g pane-border-status off
setw -g pane-border-format ""
setw -g pane-border-lines single

# Set colors
setw -g pane-active-border-style "bg=#{@thm_mantle},fg=#{@thm_mantle}"
setw -g pane-border-style "bg=#{@thm_mantle},fg=#{@thm_surface}"

